import { resolve } from 'node:path'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { FieldMetadata, ModelMetadata } from '@nest-admin/core'
import { describe, expect, it } from 'vitest'

import {
  PrismaSchemaInvalidError,
  PrismaSchemaNotFoundError,
  readPrismaDmmf,
} from '../src/metadata/read-dmmf.js'
import { toModelMetadata } from '../src/metadata/to-metadata.js'

const here = dirname(fileURLToPath(import.meta.url))
const SINGLE_FILE = resolve(here, 'fixtures/schema.prisma')
const MULTI_FILE_DIR = resolve(here, 'fixtures/multi-file')

function load(schemaPath: string): readonly ModelMetadata[] {
  return toModelMetadata(readPrismaDmmf({ schemaPath }))
}

function field(model: ModelMetadata, name: string): FieldMetadata {
  const found = model.fields.find((candidate) => candidate.name === name)
  if (!found) throw new Error(`fixture drift: ${model.name}.${name} is missing`)
  return found
}

function model(models: readonly ModelMetadata[], name: string): ModelMetadata {
  const found = models.find((candidate) => candidate.name === name)
  if (!found) throw new Error(`fixture drift: model ${name} is missing`)
  return found
}

describe('model discovery', () => {
  it('finds every model in the schema', () => {
    const models = load(SINGLE_FILE)
    expect(models.map((m) => m.name).sort()).toEqual([
      'Counter',
      'Marker',
      'Post',
      'Product',
      'Reading',
      'Tag',
      'User',
    ])
  })

  it('identifies the primary key', () => {
    const user = model(load(SINGLE_FILE), 'User')
    expect(user.primaryKey).toEqual(['id'])
    expect(field(user, 'id').isId).toBe(true)
    expect(field(user, 'email').isId).toBe(false)
  })
})

describe('field mapping', () => {
  const models = load(SINGLE_FILE)
  const user = model(models, 'User')

  it('maps scalar kinds', () => {
    expect(field(user, 'name').kind).toBe('string')
    expect(field(user, 'age').kind).toBe('number')
    expect(field(user, 'active').kind).toBe('boolean')
    expect(field(user, 'createdAt').kind).toBe('datetime')
    expect(field(user, 'role').kind).toBe('enum')
    expect(field(user, 'posts').kind).toBe('relation')
  })

  it('distinguishes required from optional', () => {
    expect(field(user, 'name').isRequired).toBe(true)
    expect(field(user, 'bio').isRequired).toBe(false)
    expect(field(user, 'age').isRequired).toBe(false)
  })

  it('identifies unique fields', () => {
    expect(field(user, 'email').isUnique).toBe(true)
    expect(field(user, 'name').isUnique).toBe(false)
  })

  it('identifies list fields', () => {
    expect(field(user, 'posts').isList).toBe(true)
    expect(field(user, 'name').isList).toBe(false)
  })

  it('exposes enum values', () => {
    expect(field(user, 'role').enumValues).toEqual(['USER', 'ADMIN'])
    expect(field(user, 'name').enumValues).toBeUndefined()
  })
})

/**
 * The distinction Phase 1 got wrong. A function default is generated by the
 * database or ORM; a literal default is an editable field that arrives
 * pre-filled. Conflating them makes `active` uneditable and `id` editable.
 */
describe('generated vs literal defaults', () => {
  const user = model(load(SINGLE_FILE), 'User')

  it('treats function defaults as generated', () => {
    expect(field(user, 'id').isGenerated).toBe(true) // @default(cuid())
    expect(field(user, 'createdAt').isGenerated).toBe(true) // @default(now())
    expect(field(user, 'updatedAt').isGenerated).toBe(true) // @updatedAt
  })

  it('does NOT treat literal defaults as generated', () => {
    expect(field(user, 'active').isGenerated).toBe(false) // @default(true)
    expect(field(user, 'role').isGenerated).toBe(false) // @default(USER)
  })

  it('exposes literal defaults for form pre-fill', () => {
    expect(field(user, 'active').defaultValue).toBe(true)
    expect(field(user, 'role').defaultValue).toBe('USER')
  })

  it('exposes no literal default for generated fields', () => {
    expect(field(user, 'id').defaultValue).toBeUndefined()
    expect(field(user, 'createdAt').defaultValue).toBeUndefined()
  })

  it('leaves plain fields alone', () => {
    expect(field(user, 'name').isGenerated).toBe(false)
    expect(field(user, 'name').defaultValue).toBeUndefined()
  })
})

describe('relations', () => {
  const models = load(SINGLE_FILE)

  it('represents a to-many relation', () => {
    const posts = field(model(models, 'User'), 'posts')
    // No `from`: the column is on the other side. Filtering or writing this
    // relation from here would have to go through Post, not through User.
    expect(posts.relation).toMatchObject({ targetModel: 'Post', cardinality: 'many' })
    expect(posts.relation?.from).toBeUndefined()
  })

  it('represents a to-one relation, and names the column it is stored in', () => {
    const author = field(model(models, 'Post'), 'author')

    expect(author.relation).toMatchObject({
      targetModel: 'User',
      cardinality: 'one',
      from: 'authorId',
      to: 'id',
    })
  })

  it('exposes the foreign key as a scalar field of its own', () => {
    // It is a real column, so it stays queryable by name. The relation
    // metadata says which relation it belongs to; it does not hide it.
    const authorId = field(model(models, 'Post'), 'authorId')

    expect(authorId.kind).toBe('string')
    expect(authorId.relation).toBeUndefined()
  })

  it('leaves scalars without relation metadata', () => {
    expect(field(model(models, 'Post'), 'title').relation).toBeUndefined()
  })
})

/**
 * Phase 1 left multi-file schema support as an open question. `getDMMF`
 * accepts `[filename, content]` tuples natively, so a directory of `.prisma`
 * files needs no concatenation and no parsing on our side.
 */
describe('multi-file schemas', () => {
  it('reads a directory of .prisma files', () => {
    const models = load(MULTI_FILE_DIR)
    expect(models.map((m) => m.name).sort()).toEqual(['Article', 'Author'])
  })

  it('resolves relations declared across separate files', () => {
    const models = load(MULTI_FILE_DIR)
    expect(field(model(models, 'Article'), 'author').relation).toMatchObject({
      targetModel: 'Author',
      cardinality: 'one',
    })
    expect(field(model(models, 'Author'), 'article').relation).toMatchObject({
      targetModel: 'Article',
      cardinality: 'many',
    })
  })
})

describe('schema failures are loud', () => {
  it('throws when an explicit schema path does not exist', () => {
    expect(() => readPrismaDmmf({ schemaPath: resolve(here, 'nope.prisma') })).toThrow(
      PrismaSchemaNotFoundError,
    )
  })

  it('throws when no schema can be auto-detected', () => {
    expect(() => readPrismaDmmf({ cwd: here })).toThrow(PrismaSchemaNotFoundError)
  })

  it('reports which paths were tried', () => {
    expect(() => readPrismaDmmf({ cwd: here })).toThrow(/prisma[\\/]schema\.prisma/)
  })

  it('surfaces Prisma validation text rather than a bare TypeError', () => {
    // getDMMF returns an error object instead of throwing; the reader must
    // detect that and raise something actionable.
    const broken = resolve(here, 'fixtures/broken')
    expect(() => readPrismaDmmf({ schemaPath: broken })).toThrow(PrismaSchemaInvalidError)
    expect(() => readPrismaDmmf({ schemaPath: broken })).toThrow(/Prisma rejected the schema/)
  })
})
