/**
 * Files on the local disk.
 *
 * The default, so an `image` widget works with nothing configured. That is the
 * whole point of it: adopting file upload should be one line in `models`, and
 * asking somebody to choose a storage backend before they can see a picture
 * appear is the wrong first step.
 *
 * ## It is a default, not a recommendation
 *
 * A container, a Vercel function and a Heroku dyno all have filesystems that
 * disappear on the next deploy. So the module warns when this store is in use
 * and the deployment looks like production - once, at startup, naming the
 * directory - because "the avatars vanished last Tuesday" is a support
 * question nobody enjoys.
 *
 * ## Keys are not paths
 *
 * A key looks like a path and must never be used as one. Every read resolves
 * the key against the root and then checks the result is still *inside* it:
 * a key is generated by the admin and cannot contain `..` today, and that is
 * exactly the kind of thing that stops being true when somebody adds a
 * migration script two years from now.
 */
import { createReadStream, createWriteStream, existsSync } from 'node:fs'
import { mkdir, rm } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'

import { AdapterError, type AdminStorage, type StoredFile } from '@nest-admin/core'

export interface LocalStorageOptions {
  /**
   * Where the files go. Relative paths resolve against the working directory.
   *
   * Defaults to `.nest-admin/uploads`, which is inside the project and easy to
   * add to `.gitignore` - and easy to notice, which a directory in a temp
   * folder would not be.
   */
  readonly directory?: string

  /**
   * The path the admin serves them from. Only used to build URLs.
   *
   * Set by the module to match the mount path; there is no reason to pass it.
   */
  readonly route?: string
}

/** Refuse a key that would escape the root, however it managed to. */
function within(root: string, key: string): string {
  const full = resolve(root, key)
  const bounded = root.endsWith(sep) ? root : root + sep

  if (full !== root && !full.startsWith(bounded)) {
    throw new AdapterError('Refusing a storage key that resolves outside the upload directory.')
  }
  return full
}

export function localStorage(options: LocalStorageOptions = {}): AdminStorage & {
  /** Read a stored file back, for the route that serves it. */
  read(key: string): NodeJS.ReadableStream | undefined
  readonly directory: string
} {
  const directory = resolve(options.directory ?? '.nest-admin/uploads')
  const route = options.route ?? '/admin/files'

  return {
    name: 'local',
    directory,

    async put(file: StoredFile): Promise<void> {
      const target = within(directory, file.key)
      await mkdir(dirname(target), { recursive: true })

      // Streamed rather than buffered: the size limit is enforced upstream by
      // the stream this consumes, so a large upload never has to be held whole.
      await pipeline(Readable.from(file.bytes), createWriteStream(target))
    },

    url(key: string): string {
      // Each segment separately: a key contains slashes that are structure, and
      // encoding the whole thing would turn them into `%2F`.
      const encoded = key.split('/').map(encodeURIComponent).join('/')
      return `${route}/${encoded}`
    },

    async remove(key: string): Promise<void> {
      await rm(within(directory, key), { force: true })
    },

    read(key: string): NodeJS.ReadableStream | undefined {
      const target = within(directory, key)
      return existsSync(target) ? createReadStream(target) : undefined
    },
  }
}

/** Whether a store is the local one, so the module knows to warn about it. */
export function isLocalStorage(storage: AdminStorage): storage is ReturnType<typeof localStorage> {
  return storage.name === 'local' && typeof (storage as { read?: unknown }).read === 'function'
}
