/**
 * Where uploaded files go.
 *
 * Three methods, because that is what an admin needs of a blob store and
 * nothing more: put one there, produce a URL somebody can open, remove it.
 * Everything about *which* file, *whether* it is allowed and *what it is called*
 * is decided before this contract is reached.
 *
 * ## Why a string column is enough
 *
 * The value stored on the record is the key this contract deals in. No new
 * table, no JSON column, no migration: most schemas already have an
 * `avatarUrl String?` sitting unused, and declaring `widget: 'image'` on it is
 * the whole adoption story.
 *
 * The cost is that a string carries no metadata - no size, no original name. So
 * the key carries what it can:
 *
 *     2026/09/k3n8vq-contract.pdf
 *     └ date  └ random  └ the original name, sanitised
 *
 * which gives back a name to display, a name to download as, and an extension
 * to derive a content type from. Size is the one thing genuinely lost, and it
 * is the one nobody has needed yet.
 *
 * ## What an implementation must not do
 *
 * Trust the key for anything but lookup. It is generated by the admin, never by
 * a client, and a store should still treat it as an opaque string rather than
 * as a filesystem path to join onto a root.
 */

/** A file on its way into storage. */
export interface StoredFile {
  /** Generated by the admin. Contains no user-controlled path segment. */
  readonly key: string
  /** Sniffed from the bytes, not taken from the request. */
  readonly type: string
  /**
   * The bytes, as a stream.
   *
   * A stream rather than a buffer so a large upload is not held in memory
   * twice - once by the admin and once by whatever the store hands it to.
   */
  readonly bytes: AsyncIterable<Uint8Array>
}

export interface AdminStorage {
  /** Stable identifier used in diagnostics and the startup warning, e.g. `'local'`. */
  readonly name: string

  put(file: StoredFile): Promise<void>

  /**
   * Where the file can be read from.
   *
   * Asynchronous on purpose: a private bucket answers with a signed URL that
   * has to be minted per request, and a contract that only allowed a synchronous
   * answer would have shut that out.
   */
  url(key: string): string | Promise<string>

  remove(key: string): Promise<void>
}

/**
 * Build the key a file will be stored under.
 *
 * The random part is what makes it unique and unguessable; the date is what
 * keeps a directory listing usable after a year; the name is what a person sees
 * when they download it again.
 *
 * The original name is reduced to something that cannot be a path: no
 * separators, no leading dots, no control characters, and a length cap. It is
 * decoration - the file is found by the random part - so mangling it is always
 * safer than preserving it.
 */
export function storageKeyFor(originalName: string, random: string): string {
  const now = new Date()
  const month = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, '0')}`

  return `${month}/${random}-${safeName(originalName)}`
}

/**
 * The original name, reduced to something that cannot be read as structure.
 *
 * An allowlist rather than a list of characters to strip. The first version of
 * this was a denylist and shipped with a broken character class - a stray range
 * swallowed the space it was meant to replace, so `ada avatar.png` became a key
 * with a space in it. A denylist fails open by nature: everything forgotten is
 * permitted, and the forgetting is silent.
 *
 * Unicode letters, digits, dots and underscores survive - an allowlist of
 * ASCII would have turned every non-Latin filename into a dash, which is the
 * wrong answer for most of the world. Everything else becomes a
 * dash, runs collapse, and the result is capped. The name is decoration - the
 * file is found by the random part of the key - so mangling it is always safer
 * than preserving it.
 */
export function safeName(name: string): string {
  const cleaned = name
    .replace(/[^\p{L}\p{N}._]+/gu, '-')
    // `..` is the one sequence that means something to a path resolver.
    .replace(/\.{2,}/g, '.')
    .replace(/^[.-]+/, '')

  // A name made entirely of replaced characters still has to be something.
  return cleaned === '' ? 'file' : cleaned.slice(0, 100)
}

/** The original name a key was built from, for display and for downloading. */
export function nameFromKey(key: string): string {
  const last = key.split('/').at(-1) ?? key
  const dash = last.indexOf('-')
  return dash === -1 ? last : last.slice(dash + 1)
}
